NeonGeckoCom/skill-user_settings

requirements.txt, setup.py, skill.json, test/test_skill.py
=> Remove package_data print that breaks getting version string

__init__.py, locale/en-us/languages.value, test/test_skill.py
Ensure all Coqui TTS languages are resolved
Move language overrides to .value file for language support
Update unit tests to include all TTS supported languages
Refactor language resolution to skip LF if manually specified
=> Better language resolution

locale/en-us/languages.value, test/test_skill.py
Add remaining languages from CoquiTTS and LibreTranslate lists
=> Added LibreTranslate and Coqui Languages with Tests

.github/workflows/skill_tests.yml, requirements.txt, skill.json
Update neon-utils dependency to stable version
Cleanup dependency installation in unit test workflows
=> Update dependencies and unit test automation

__init__.py, locale/en-us/dialog/location_uknown_offline.dialog, locale/en-us/dialog/location_unknown_online.dialog, test/test_skill.py
Handle undefined user location with online/offline dialog
Add unit tests for location changes
=> Handle unset location responses

__init__.py, locale/en-us/dialog/error_change_username.dialog, locale/en-us/regex/setting.rx, locale/en-us/vocab/audio.voc, locale/en-us/vocab/change.voc, locale/en-us/vocab/deny.voc, locale/en-us/vocab/full.voc, locale/en-us/vocab/hesitation.voc, locale/en-us/vocab/language_settings.intent, locale/en-us/vocab/language_stt.intent, locale/en-us/vocab/language_tts.voc, locale/en-us/vocab/my_name_is.voc, locale/en-us/vocab/no_secondary_language.voc, locale/en-us/vocab/tell_me_my.voc, locale/en-us/vocab/where_am_i.intent, test/test_intents.yaml, test/test_skill.py
Add intent tests with intent fixes/improvements
=> Implement intent tests

__init__.py
This is just a patch, consider refactoring to better handling after https://github.com/OpenVoiceOS/ovos-PHAL-plugin-ipgeo/pull/5
=> Add patch to retry geolocation update if failed on first attempt

__init__.py, requirements.txt, skill.json, test/test_skill.py
Adds runtime_requirements property for better skill loading
=> Add Runtime Requirements

__init__.py, locale/en-us/dialog/birthday_is.dialog, locale/en-us/dialog/birthday_not_known.dialog, locale/en-us/intent/when_is_my_birthday.intent, test/test_intents.yaml, test/test_resources.yaml, test/test_skill.py
Adds intents, intent handler, and tests to handle a user request to have their birthday read back to them
Closes #50
=> Add intent to speak back birthday with unit and intent tests

test/test_skill.py
Explicitly set timezone in unit tests to prevent test failures
Closes #70
=> Add timezone to test profile

requirements.txt, skill.json
=> Update neon-utils to stable dependency spec

requirements.txt, skill.json
=> Loosen ovos_utils dependency

requirements.txt, skill.json
Updates alpha dependencies to stable versions
=> Update dependencies to stable releases

.github/workflows/push_skill_json.yml, .github/workflows/skill_tests.yml, __init__.py, test/test_skill.py
Add debug logging to troubleshoot email address transcriptions
Remove duplicated method from base class
Update tests to address user feedback
=> Add logging and test coverage for reported email parsing bug

__init__.py
Refactor init/initialize for ovos-workshop compat
Troubleshooting user configuration updates
=> Config fixes and init refactor

__init__.py
Emit a message to update weather when location or units are changed.
=> Update weather on preference changes

__init__.py
Override user location populated from defaults with geolocation
=> Better default location handling

__init__.py
Fixes language handling in "speak to me" intent handling
Probably introduced in #81
Resolves bug reported by @neonjosh
=> Fix TTS Intent Language Bug

requirements/test.txt, test/test_skill.py
=> Update test dependencies to stable specs

__init__.py, requirements/test.txt
Update test dependency to stable spec
Fix spelling in docstring
=> Update test dependency and fix docstring

__init__.py, requirements.txt, skill.json, test/test_skill.py
Update `mycroft` module imports
Update requirements.txt
=> Remove `mycroft` imports

__init__.py, test/test_skill.py
Refactor `translate` to `resources.render_dialog`
Refactor `self.update_profile` to `update_user_profile`
Includes patch and test update to account for upstream API change
=> Remove deprecated references

__init__.py, test/test_intents.yaml, test/test_skill.py
Add parsing and test coverage to handle trailing '.' in matched utterance
Closes #114
=> Improved input utterance parsing

.github/workflows/skill_tests.yml, __init__.py, requirements.txt, skill.json, test/test_skill.py
Update dependencies to allow 0.x ovos dependencies
Update imports
Related to https://github.com/NeonGeckoCom/NeonCore/pull/708
=> Update OVOS depdendencies for 0.x compat
